services:
  pocketbase:
    build:
      context: ./pocketbase  # This points to the directory with your Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    #ports:
      #- '8181:8080'  # Expose Pocketbase on port 8181
    networks:
      - app-network

    profiles:
      - dev
      - production

  qrapp:
    image: node:18-alpine
    container_name: qrapp  # Added container name for clarity
    working_dir: /usr/src/app
    volumes:
      - ./qrapp:/usr/src/app
    #ports:
      #- '3000:3000'  # Expose Node.js app on port 3000
    depends_on:
      - pocketbase  # Ensure Pocketbase starts before qrapp
    command: node /usr/src/app/server/index.js  # Keeps the container running
    networks:
      - app-network
    profiles:
      - dev
      - production

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
      - exposed-network # Use a custom network for the proxy
    profiles:
      - production

  nginx:
    image: nginx:latest  # Use the latest NGINX image
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"  # Map port 80 of the host to port 80 of the container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Mount the configuration files
    networks:
      - app-network
      - exposed-network # Use a custom network for the proxy
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

  exposed-network:
    driver: bridge
