services:
  pocketbase:
    build:
      context: ./pocketbase  # This points to the directory with your Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    networks:
      - app-network
    profiles:
      - dev
      - production

  qrapp:
    image: node:18-alpine
    container_name: qrapp  # Added container name for clarity
    working_dir: /usr/src/app
    volumes:
      - ./qrapp:/usr/src/app
    environment:
      - POCKET_USER=abinadi.swapp@nsanpete.org
      - POCKET_PASSWORD=fakepassword
    depends_on:
      - pocketbase  # Ensure Pocketbase starts before qrapp
    command: node /usr/src/app/server/index.js  # Keeps the container running
    networks:
      - app-network
    profiles:
      - dev
      - production

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=randomdomain-url-etc.online
      - SUBDOMAINS=wildcard
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - app-network
      - exposed-network  # Use a custom network for the proxy
    profiles:
      - production

  nginx:
    image: nginx:latest  # Use the latest NGINX image
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - swag  # Ensure SWAG starts before nginx
    ports:
      - "80:80"  # Map port 80 of the host to port 80 of the container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Mount the configuration files
    networks:
      - app-network
      - exposed-network  # Use a custom network for the proxy
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
  exposed-network:
    driver: bridge
